local keymaps = require("keymaps")
keymaps.setup()
require("vimOptions")

keymaps.setupNvimPreLazy()
require("config.lazy")
require("templates").setup()
require("userCmds")
keymaps.setupNvim()
require("autoCmd")
