import? "~/.config/work.justfile"

default:
    just --justfile {{justfile()}} --list

hello:
    echo "Hello from global justfile!"

sync-ai-markedown-files:
    @./sync_ai_md.sh

# terminal
devcontainer-build:
    devcontainer build --workspace-folder .

# terminal
devcontainer-up:
    devcontainer up --workspace-folder .

# terminal
devcontainer-exec:
    devcontainer exec --workspace-folder . zsh


